# Generated by Django 6.0 on 2025-12-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employee_role'),
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karaokeorderitem',
            old_name='product',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='karaokeorderitem',
            old_name='price_at_order',
            new_name='price_at_time',
        ),
        migrations.RemoveField(
            model_name='karaokeorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='karaokeroom',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='karaokeorder',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.outlet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='karaokeroom',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='KaraokeBooking',
        ),
    ]
