# Generated by Django 6.0 on 2025-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_rename_product_karaokeorderitem_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaokesession',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='karaokesession',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='karaokesession',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='karaokesession',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='karaokesession',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
