# Generated by Django 6.0 on 2025-12-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_karaokesession_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karaokesession',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('MVR', 'Maldivian Rufiyaa')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='karaokesession',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='karaokesession',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=15.42, max_digits=10),
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
