# Generated by Django 6.0 on 2025-12-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_karaokesession_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karaokesession',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='karaokeorder',
            name='is_pos_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='karaokeorder',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='karaoke.karaokesession'),
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
