# Generated by Django 6.0 on 2025-12-21 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0005_remove_karaokesession_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField(default=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='karaokeorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='karaokeorderitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='karaokeroom',
            name='outlet',
        ),
        migrations.RenameField(
            model_name='karaokesession',
            old_name='total_price',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='customer_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='karaokesession',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karaoke.room'),
        ),
        migrations.CreateModel(
            name='SessionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='karaoke.karaokesession')),
            ],
        ),
        migrations.DeleteModel(
            name='KaraokeOrder',
        ),
        migrations.DeleteModel(
            name='KaraokeOrderItem',
        ),
        migrations.DeleteModel(
            name='KaraokeRoom',
        ),
    ]
