# Generated by Django 6.0 on 2025-12-22 04:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_unit_price_saleitem_price_and_more'),
        ('karaoke', '0006_outletsetting_room_remove_karaokeorderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('VIP', 'VIP Room'), ('Standard', 'Standard Room')], default='Standard', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
        ),
        migrations.RemoveField(
            model_name='karaokesession',
            name='room',
        ),
        migrations.RemoveField(
            model_name='sessionorder',
            name='session',
        ),
        migrations.DeleteModel(
            name='OutletSetting',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='KaraokeSession',
        ),
        migrations.DeleteModel(
            name='SessionOrder',
        ),
    ]
