# Generated by Django 6.0 on 2025-12-22 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_unit_price_saleitem_price_and_more'),
        ('karaoke', '0008_bookingrequest_outletsetting_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='outletsetting',
            name='currency_symbol',
        ),
        migrations.AddField(
            model_name='outletsetting',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='RoomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_served', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='karaoke.roomsession')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='karaoke.roomorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
