# Generated by Django 5.2.9 on 2025-12-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_creditpayment_outlet_customer_outlet_and_more'),
        ('karaoke', '0009_remove_bookingrequest_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='roomorder',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_orders', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='roomorderitem',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_order_items', to='core.outlet'),
        ),
    ]
