# Generated by Django 5.2.9 on 2025-12-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_creditpayment_outlet_customer_outlet_and_more'),
        ('karaoke', '0010_bookingrequest_outlet_roomorder_outlet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='room',
            name='min_booking_duration',
            field=models.IntegerField(default=60, help_text='Minimum duration in minutes'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_minute',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Rate for partial minutes', max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('VIP', 'VIP Room'), ('Standard', 'Standard Room')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Active', 'Active'), ('Cleaning', 'Cleaning')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karaoke_rooms', to='core.outlet'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Base hourly rate', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('outlet', 'name')},
        ),
        migrations.CreateModel(
            name='KaraokeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When session actually started', null=True)),
                ('paused_at', models.DateTimeField(blank=True, help_text='When session was paused', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When session was ended/closed', null=True)),
                ('booked_duration_minutes', models.IntegerField(default=60, help_text='Originally booked duration')),
                ('actual_duration_minutes', models.IntegerField(default=0, help_text='Actual time consumed (excluding pauses)')),
                ('total_pause_minutes', models.IntegerField(default=0, help_text='Total time paused')),
                ('extra_time_minutes', models.IntegerField(default=0, help_text='Extra time added during session')),
                ('base_rate', models.DecimalField(decimal_places=2, default=100, help_text='Rate per hour at session start', max_digits=10)),
                ('room_charge', models.DecimalField(decimal_places=2, default=0, help_text='Base room charge', max_digits=10)),
                ('extra_time_charge', models.DecimalField(decimal_places=2, default=0, help_text='Extra time charges', max_digits=10)),
                ('food_beverage_charge', models.DecimalField(decimal_places=2, default=0, help_text='F&B charges from orders', max_digits=10)),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, help_text='Grand total', max_digits=10)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karaoke_sessions', to='core.outlet')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='karaoke.room')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='RoomSession',
        ),
        migrations.AddIndex(
            model_name='karaokesession',
            index=models.Index(fields=['outlet', 'status'], name='karaoke_kar_outlet__e8458e_idx'),
        ),
        migrations.AddIndex(
            model_name='karaokesession',
            index=models.Index(fields=['started_at'], name='karaoke_kar_started_e34161_idx'),
        ),
        migrations.CreateModel(
            name='RoomSession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('karaoke.karaokesession',),
        ),
    ]
