# Generated by Django 5.2.9 on 2025-12-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_creditpayment_outlet_customer_outlet_and_more'),
        ('karaoke', '0011_alter_room_options_room_min_booking_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomSession',
        ),
        migrations.CreateModel(
            name='RoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When session actually started', null=True)),
                ('paused_at', models.DateTimeField(blank=True, help_text='When session was paused', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When session was ended/closed', null=True)),
                ('booked_duration_minutes', models.IntegerField(default=60)),
                ('actual_duration_minutes', models.IntegerField(default=0)),
                ('total_pause_minutes', models.IntegerField(default=0)),
                ('extra_time_minutes', models.IntegerField(default=0)),
                ('base_rate', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('room_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_time_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_beverage_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karaoke_sessions', to='core.outlet')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='karaoke.room')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='RoomOrder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='karaoke.roomsession'),
        ),
        migrations.DeleteModel(
            name='KaraokeSession',
        ),
    ]
