# Generated by Django 6.0 on 2025-12-19 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_cost_price_product_selling_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='note',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=10),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='table_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
