# Generated by Django 6.0 on 2025-12-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_item_price_saleitem_price_at_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
