# Generated by Django 6.0 on 2025-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='primary_currency',
            field=models.CharField(choices=[('USD', '$ USD'), ('MVR', 'Rf MVR')], default='MVR', max_length=3),
        ),
    ]
