# Generated by Django 6.0 on 2025-12-21 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_outlet_primary_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saletransaction',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='quantity',
            new_name='adjustment_amount',
        ),
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='saletransaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='saletransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='saletransaction',
            name='table_name',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='outlet',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.outlet'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='primary_currency',
            field=models.CharField(default='MVR', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.outlet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
