# Generated by Django 6.0 on 2025-12-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_date_saletransaction_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saletransaction',
            name='customer',
        ),
        migrations.RenameField(
            model_name='saletransaction',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='adjustment_amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='primary_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock_threshold',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outlet',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='No category', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
