# Generated by Django 6.0 on 2025-12-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Bank Transfer'), ('Card', 'Card'), ('Credit', 'Customer Credit')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='table_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.saletransaction'),
        ),
    ]
