# Generated by Django 5.2.9 on 2025-12-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customer_notes_customer_visit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payments', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='customer',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.outlet'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.outlet'),
        ),
    ]
