# Generated by Django 5.2.9 on 2025-12-24 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_creditpayment_outlet_customer_outlet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Adjustment', 'Adjustment'), ('Spoilage', 'Spoilage'), ('Transfer', 'Transfer')], default='Sale', max_length=20)),
                ('quantity_changed', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('previous_level', models.IntegerField(default=0)),
                ('new_level', models.IntegerField(default=0)),
                ('reference', models.CharField(blank=True, help_text='Transaction ID, PO number, etc.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='core.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['outlet', 'created_at'], name='core_invent_outlet__1cedd9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['product', 'created_at'], name='core_invent_product_0df28e_idx'),
        ),
    ]
