# Generated by Django 5.2.9 on 2025-12-24 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_inventorylog_delete_stockadjustment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('outlet', 'user')},
        ),
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='For Permanent: Monthly salary, For Commission: Min salary, For Daily: Daily rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission % for commission-based employees', max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(choices=[('P', 'Permanent (Fixed Monthly)'), ('C', 'Commission-Based'), ('D', 'Daily-Rated')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.outlet'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of attendance')),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Calculated hours worked', max_digits=5)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.employee')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.outlet')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['outlet', 'date'], name='core_attend_outlet__e95b5b_idx'), models.Index(fields=['employee', 'date'], name='core_attend_employe_7ab622_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Calculated', 'Calculated'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.employee')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.outlet')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['outlet', 'year', 'month'], name='core_payrol_outlet__ab195c_idx')],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
