# Generated by Django 5.2.9 on 2025-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload outlet logo/branding image', null=True, upload_to='outlet_logos/'),
        ),
    ]
